language:
  - node_js
node_js:
  - 5.0.0
before_script:
  - git config --global user.email "nobody@nobody.io"
  - git config --global user.name "Travis CI"
  - npm install -g grunt-cli@0.1.13
  - npm install -g bower@1.6.5
  - bower install -f
script:
  - grunt deploy

env:
  global:
  - secure: UlRnVLIVE2zCo2XfHjFFgoMAvJslOrPRV8To01d9uCF5Vo/K/atu5WXgdVWykfCwTH5yoCyqFGF5Au4CxcZ4TjgUkApRLaPsPIdnbyVa7IiDveBESbbnyb2RWXpzRp9u/MP50Ojte358yvkWWkErx0SLvuK9h1rDJgdFql2BemlopDORQrLZLkCu/vlG7ILO0zTMAjrAJsnEOd4EUl8Cl5t/U52e+4rqW666gNqgt7+WRXS3eWOGO1YFc/ijezEjga8rQlSODt1UdI4aYGqDTSWKv+t0ld2K2n09jN7T+qMp5zz/kdEdc6HDqVaZK7KUazx2xkFzerQxoe0SQh1TvN7Y3smhjHpzlx9kj9ogffsEbNYPHk6flxnUH/a3Ka8ENO+2ueKDB0beqrbfnqnA8Iqtwfx6435LgJa0vyoa9ej20XbelGhRVynoZAi34R0vr1ABvidiF0wYdufqc+gK7Tk/VtNBkwUrREei4aesrNrAwCqi27N1tJIl/049UszdO3GxK0nvJIusDHPs6+LMK/usbe+u7LqbxyaZdydVcxpGrICorM8gf9jJ3Eo/aoBW775tVpQhb73pCIf/pllWwk0Vm5LOmTcThSuMd7CNI4FU9YVtN+7lVjWrGXF81wbdOJh+tfstd608w1dHhJWv1oVf6cJwnOudSX3VyRO6gAE=
